### PR TITLE
Try to search for eslint in subfolder for nested projects 

### PR DESCRIPTION
**Pull request by tomastrajan**
(opened in Intellij IDEs)

### CODE REVIEW

**Comment by tomastrajan** [comment]
Ok I reworked it based on your input.

**Comment by mantoni** [comment]
Cool, thanks! I have two questions:

- Why are you using only the first part of the file path? That seems a bit specific for your use-case.
- Are you sure this works without joining `cwd` and the file path?

**Comment by tomastrajan** [comment]
Yeah, basically I am bit overworked & don't focus anymore :)) `cwd` must be prepended before `filename.split(path.sep)[0] ` like `cwd + path.sep + filename.split(path.sep)[0] `.

As for the parts of path, it would be possible to start as deep as possible because as you said, `resolve` looks recursively up the parent folders. That would mean we should get 

```javascript
cwd + path.sep + filename.split(path.sep).pop().join(path.sep)
```

**Comment by mantoni** [comment]
Or even `path.join(cwd, path.dirname(filename))`.

As a side note: This whole thing just shows how urgently I need to add test cases for the whole project. There is a lot of potential to cause damage, even with a simple change.

**Comment by tomastrajan** [comment]
Yeah, I don't know node APIs that well but it looks much nicer & simpler. Tests make thing always easier.

**Comment by mantoni** [comment]
Did you try this version with IntelliJ?

**Comment by tomastrajan** [comment]
Will check it out when I am back

**Comment by mantoni** [comment]
This cannot be merged anymore. Can you please check if the situation changed with eslint_d 3.0.0? I'm now passing `cwd` to eslint which might help with your situation as well.

**Comment by mantoni** [comment]
This is now quite old and has conflicts. It's not that much code, so closing. If you still want this feature, please open a new PR. Cheers.

**Pull request closed without merging**
