### PR TITLE
feat: adapt to new eslint flat config

### PR DESCRIPTION
**Pull request by amritk**
Alright got something to work with now. Let me know what you think of this strategy. Also not sure about some of the new config so I have them commented out for now.

### CODE REVIEW

**Comment by amritk** [comment]
I'm testing in neovim and the speed is back!! Thanks for this package btw @mantoni, cant really live without it now.

**Comment by mantoni** [comment]
Great! I like how minimal this change turns out to be. Since this is still an experimental feature with opt-in, I wouldn't worry about the config for now and just remove the commented out options. We can add those later if someone requires a specific option.

Can you fix the one linter issue and add tests for this? Then I'll release it in a minor. 🚀

**Comment by amritk** [comment]
Done! cheers

**Comment by amritk** [comment]
@mantoni alright check out the tests, do they work?

**Comment by mantoni** [comment]
Weird. There are linter issues with files you didn't touch. I'll check tomorrow.

**Comment by amritk** [comment]
Ah I added a flat config lint file for testing, it's probably picking that up. Maybe I'll switch to mock testing

**Comment by mantoni** [comment]
Or you put the config file into `test/fixture` and run in that cwd?

**Comment by amritk** [comment]
Alright good idea! Done

**Comment by mantoni** [comment]
Fantastic! 📦 Released in `v13.1.0`. Thank you so much for contributing @amritk ❤️

**Pull request merged**
