### PR TITLE
Support --print-config

### LINKED ISSUE #50: Support --print-config
flycheck-eslint now uses `--print-config` to verify that a file has a config. This doesn't work in `eslint_d`, effectively disabling it.

### PR DESCRIPTION
**Pull request by aaronjensen**
Fixes #50

### CODE REVIEW

**Comment by aaronjensen** [comment]
Thanks for the quick merge. If you get a chance to release a new version it'd be much appreciated. Thanks!

**Comment by mantoni** [comment]
Released in `v4.1.0`. Thank you!

**Comment by aaronjensen** [comment]
eerie

**Comment by cpitclaudel** [comment]
👍  👏

**Pull request merged**
