### PR TITLE
Adjust cwd for nested projects (found in Intellij IDEs)

### PR DESCRIPTION
**Pull request by tomastrajan**
Hi Max,

I had to add also `fs.existSync` check to only do it if the projects are really nested. This solution supports nesting with depth = 1. 

Use of `fs` is not expensive, did couple of runs and it was something like `fs: 0.667ms`

### CODE REVIEW

**Comment by mantoni** [comment]
Cool, thanks! Why did you skip the idea of doing this check only for `--stdin` and if `--stdin-filename` is not the top of the cwd? I'm not convinced that it's a good idea to look for `package.json`.

**Comment by tomastrajan** [comment]
The thing is that `pwd` and path in `filename` will trigger previously discused logic also in cases without nesting which would cause problems by chaning `cwd` to any first folder in the filename path. 

For example: `C:\dev\projects\project-a` can have `filename` like `lib\file.js`, there is no way to know if the `lib` part is project root or some valid folder inside of the project. Thats why I used check for `package.json` to determine if it's really a project root we are dealing with.

On the other hand, nested projects work without any fix by default, it only doesn't work if you provide eslint rules as a npm package (by extending) as in our case. Only then the correct `cwd` is important.

**Comment by mantoni** [comment]
Yes, but one might want to lint a file in a project that does not have a `package.json` (yet).

If the thing that doesn’t work is loading the `extends` in the `package.json`, then it might be a bug in eslint. At least, this could be added there, because they’re resolving the directory where the config is and we shouldn’t duplicate the logic in `eslint_d`.

What do you think?

**Comment by tomastrajan** [comment]
Yes, the argument that we want to lint non `package.json` project is very important. I'll check how is it done in `eslint` itself and maybe will be able to come up with solution.

**Comment by mantoni** [comment]
Ok, so after the discussion [on the eslint issue tracker](https://github.com/eslint/eslint/issues/4973), I had fresh look. What was discussed there is not entirely correct, because eslint_d loads and uses the eslint module that is installed in the project. However, this isn't working correctly with InelliJ in this particular case, bacause I'm looking for eslint in the cwd (see https://github.com/mantoni/eslint_d.js/blob/master/lib/linter.js#L33).

A possible fix could be to use the given filename as the base to resolve the module and fallback to the cwd if no filename was given. It should then find the correct eslint module with the correct configs and it should also load the plugins correctly.

Fancy giving that a shot?

**Comment by tomastrajan** [comment]
Yeah, sounds good. I'll look into it.

**Pull request closed without merging**
